-- Add missing Owner fields
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "cuisineType" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "seatingCapacity" INTEGER;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "restaurantType" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "outletCount" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "billTemplate" TEXT NOT NULL DEFAULT 'CLASSIC';
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "gstin" TEXT;

-- Add missing Order fields
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "isExcluded" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "excludedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "excludedBy" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "excludedReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
